### PR TITLE
Adds User Authentication and Query Submission capabilities 

### PR DESCRIPTION
**Pull request by bdolly**
CLOSES PR #55, #93 
CLOSES issue #27 

This adds the ability to auto-login to the application upon first visit which saves a cookie to the local machine with the created user object. This cookie value is then used to authenticate POST request when creating a classifier. 
**note: unit tests have not yet been written for this and thus CI test will fail

### CODE REVIEW

**Comment by bdolly** [comment]
@dhimmel you're call whether to merge and deploy this

**Comment by dhimmel** [comment]
I'll discuss with @dcgoss on Monday. There are conflicts in two files, but it looks like they're of the simple type that [GitHub can resolve](https://github.com/blog/2293-resolve-simple-merge-conflicts-on-github) online.

> you're call whether to merge and deploy this

For what reason, wouldn't we merge/deploy this? Does this prevent login by slug-url?

**Comment by dcgoss** [comment]
Checking it out!

**Comment by dcgoss** [comment]
Currently have been trying to figure out how to get this thing to build properly. I'm getting hit with this error: 
screen shot 2017-07-17 at 4 32 18 pm. I've tried removing the `node_modules` directory and rerunning `npm install` but it hasn't worked. Looks like it has something to do with https://github.com/angular/angular.js/issues/15788

**Comment by bdolly** [comment]
@dhimmel no reason to not deploy/merge just wasn't sure what the status of automated deployment was as I haven't kept up on that. 

@dcgoss seems like you may just need to adjust the version of angular-mocks in the `package.json` to one that is compatible with Angular v1.5.x

**Comment by dcgoss** [comment]
So if you remove your node_modules directory and run `npm install` it works for you?

**Comment by dcgoss** [comment]
Fixed it. I had to remove the `bower_components` directory

**Comment by dcgoss** [comment]
Everything looks good when the page first loads:
screen shot 2017-07-17 at 5 07 04 pm

As soon as I enter the disease search section, the progress bar disappears and I can't see how to submit the classifier:
screen shot 2017-07-17 at 5 06 31 pm

**Comment by dcgoss** [comment]
Getting an error about missing fonts: 
screen shot 2017-07-17 at 5 09 21 pm

**Comment by bdolly** [comment]
@dhimmel how are you viewing this? pulling the PR down to a branch and running locally?

**Comment by dcgoss** [comment]
@bdolly if that was meant for me I’m cloning your repo and running it from there

**Comment by bdolly** [comment]
@dcgoss @dhimmel are you guys encountering issues working off of my most recent `develop` branch? just trying to figure out where to debug.

**Comment by dcgoss** [comment]
Cloned the repo and switched to develop branch.
screen shot 2017-07-18 at 11 15 59 am

`rm -rf node_modules/`
`npm install`

`npm run-script build` output:
screen shot 2017-07-18 at 11 23 14 am

`npm run-script dev` output:
screen shot 2017-07-18 at 11 24 15 am

`localhost:3000` console:
screen shot 2017-07-18 at 11 24 50 am

**Comment by bdolly** [comment]
@dcgoss @dhimmel  I just pushed some fixes up for the fonts issue and I think the package.json for angular-growl-v2. 

However I switched the api base over to`api.cognoma.org` and ran into a host of CORS issues with the `/samples`  and `/users` endpoints 
screen shot 2017-07-18 at 12 23 44 pm

First issue is with `/users/<random_slug>` which is used by the UserAuth service for authenticating a user cookie. I also am not able to load the Django REST API in the browser by going to `api.cognoma.org/users` to check and make sure users are getting created in the DB. The `/users` endpoint is also being slow so when you fire up the app locally you don't get a notification for several seconds that you've been logged in because the Auth service is promise based. 

The second issue is with `/samples?disease=<disease_acronyn>` seems like it doesn't have `Access-Control-Allow-Origin: * ` set to allow it to be used while developing locally but this should be resolved once deployed as the call will be same origin.

**Comment by dcgoss** [comment]
@bdolly any time you access api.cognoma.org make sure it is over HTTPS, otherwise your request will hang. Also are you still seeing issues with the progress bar as you switch between selecting genes and diseases?

**Comment by bdolly** [comment]
@dhimmel no the progress bar is working as expected

**Comment by dcgoss** [comment]
@bdolly try Safari

**Comment by dcgoss** [comment]
Looks like the submit works!! Awesome job 🎉
If a user already knows their slug should we provide a way to authenticate that way instead of as a new guest user?

**Comment by bdolly** [comment]
@dhimmel @dcgoss currently the front-end is only tested in Chrome just to get the MVP functionality down. I am currently working on a better [Bootstrap dashboard layout branch](https://github.com/bdolly/cognoma-frontend/tree/bootstrap-dashboard-layout) that should be better cross-browser and possibly mobile down the line. Hoping to port the existing functionality over to it this weekend and maybe get the User/Profile login in there as well.

**Comment by dcgoss** [comment]
@bdolly sounds like a plan! Thanks so much for all your effort thus far, we are literally right at the edge of going live with Cognoma. Today the first notebooks were processed entirely through the API on our deployment cluster! Almost done making a few polishes on core-service and ml-workers and then as soon as we can get frontend ready we should be set.

If the purpose of this PR is to auto-login as guest user and submit, it appears that is working as expected so I approve these changes.

**Comment by bdolly** [comment]
@dcgoss @dhimmel this should be good to merge to `production` branch and deploy, the unit tests will still fail but the functionality is there

**Comment by dcgoss** [comment]
@bdolly I will manually deploy right now. https://github.com/cognoma/frontend/pull/92 implements automatic deployment with CircleCI, however the deployment only happens if the tests pass so it wouldn't function properly anyway at this stage

**Comment by dcgoss** [comment]
Currently having some access permissions with AWS but will get it up as soon as I can

**Comment by dcgoss** [comment]
Deployed!

**Pull request merged**
