### PR TITLE
1.0 Redesign

### PR DESCRIPTION
**Pull request by dcgoss**
This PR includes many small UI refinements and improvements, in addition to updates to error handling and API access. This PR is currently deployed as a test on cognoma.org. 

In combination with the just-merged https://github.com/cognoma/core-service/pull/87, this PR takes cognoma to v1.0! :tada:

### CODE REVIEW

**Comment by dcgoss** [comment]
https://github.com/cognoma/frontend/pull/95 should be merged before this is merged

**Comment by dcgoss** [comment]
Figured I should request a review before merging. It's a big PR but you can try it out right now on cognoma.org

**Comment by bdolly** [comment]
@dcgoss haven't had a chance to pick through the code yet but the UI is looking better. Great job on this. Cant' wait to show you guys the re-re-designed interface I've been working on and start making progress on Query Analytics and Query Review stuff!

**Comment by dcgoss** [comment]
@bdolly Thank you and that sounds great! Should I merge this PR for now?

**Comment by bdolly** [comment]
@dcgoss I'll give it a closer look tonight. Are you coming to the meetup tomorrow?

**Pull request merged**
