### PR TITLE
adds unit test runner to $npm run dev task

### PR DESCRIPTION
**Pull request by bdolly**
starts karma test runner and browsersync to show/update unit test reports on file save

also adds a missing "ui-router-route-to-components": "^0.1.0", to package.json

### CODE REVIEW

**Comment by bdolly** [comment]
@awm33 I rolled the unit test in the front-end dev workflow, regarding CI from https://github.com/cognoma/frontend/issues/32 it probably needs some environment variables thrown in down the line to work with CI.

**Comment by awm33** [comment]
@bdolly We can [add environment variables to CircleCI](https://circleci.com/docs/environment-variables/)

**Comment by bdolly** [comment]
@dhimmel @awm33  any objection to merging this, if not I'm going to merge it in so I can start making unit test PRs

**Comment by dhimmel** [comment]
> any objection to merging this

Fine with me. We should probably revisit our merging policy so maintainers can merge stagnant pull requests like this.

**Pull request merged**
