### PR TITLE
Adds Disease Type and Mutations Query Sets

### PR DESCRIPTION
**Pull request by txnnxr**
#26 #25 
Adds Components:
querySetDiseaseType
querySetMutations
geneCard
diseaseCard

Hey @bdolly, mind taking a look at this and giving me some feedback when you get a chance?

### CODE REVIEW

**Comment by bdolly** [comment]
@txnnxr this is some good stuff man. matches up with the routes and all the bindings and component state functions looks solid for now. Few little points with the styling is maybe try and use semantic names for the text headlines instead of nesting tag selectors in the scss but that's a really minor point for now. 

@dhimmel I'm good to merge this in if you are.

**Comment by dhimmel** [comment]
> @dhimmel I'm good to merge this in if you are.

Your call. Did you want to give @txnnxr a chance to address:

> use semantic names for the text headlines instead of nesting tag selectors in the scss

**Comment by txnnxr** [comment]
@bdolly Thank you! As far as the CSS goes I have couple other things I have to get done so I could clean it up either tonight or early tomorrow. Or if you want to merge this now just to check it off I can just include it with the next PR.
@dhimmel

**Comment by bdolly** [comment]
@txnnxr the css stuff is a super minor issue and really more of a developer preference thing. I'm going to go ahead and merge this in and we can polish it in future PRs

**Pull request merged**
