### PR TITLE
Adds CircleCI env vars for Karma and Protractor test

### PR DESCRIPTION
**Pull request by bdolly**
Adds unit tests for on_config.js to test angular ui-router states and routes

### CODE REVIEW

**Comment by bdolly** [comment]
@awm33 I added the CircleCI vars to the karma and protractor configs but couldn't find a var to use for the JOB_NUMBER. The testing setup was originally configured to use [Travis](https://travis-ci.org/) and the env vars for that so I just converted them over to CircleCI. The `process.env.TRAVIS_JOB_NUMBER` was used to set the `tunnelIdentifier` property for SauceLabs integration if gives you more of an idea.

**Comment by awm33** [comment]
@bdolly You could try using CIRCLE_SHA1 as a build identifier

**Comment by bdolly** [comment]
@awm33 looks like this PR CirlceCI check failed due to the fact that we don't have a [SauceLabs ](https://saucelabs.com/B)account and it's trying to launch and run test through SauceLabs. I am unfamiliar with SauceLabs, do you think it's something necessary for our CI testing or is it just another CI runner?

**Comment by cgreene** [comment]
I have a saucelabs account for open source projects if we want to use it.
Happy to hook it up if it's desired.

**Comment by bdolly** [comment]
@cgreene can you explain what the difference between CircleCI and SauceLabs is as I'm new to the world of CI testing? Is SauceLabs a cross browser testing platform for CI similar to BrowserStack?

**Comment by cgreene** [comment]
I wasn't previously familiar with BrowserStack. From a quick glance at
their page they seem to be offering a similar service to what SauceLabs
offers.

**Comment by bdolly** [comment]
@cgreene ok cool I thought they were similar. If you want to hook SauceLabs up to the front-end cI stuff I don't see how it would hurt to have more test coverage. 

Let me know if there's anything I need to adjust in the proctractor or karma configs for it, looks like it's set using 
`sauceUser: process.env.SAUCE_USERNAME,`
`  sauceKey: process.env.SAUCE_ACCESS_KEY`

**Comment by bdolly** [comment]
@dhimmel not sure how to resolve these conflicts, I followed the command line instructions with no luck

**Comment by dhimmel** [comment]
> @dhimmel not sure how to resolve these conflicts, I followed the command line instructions with no luck

@bdolly I got an email with the above comment. Did you resolve the conflicts? It doesn't look like there are any outstanding conflicts according to GitHub.

**Comment by bdolly** [comment]
@dhimmel yeah figured it out shortly after I posted it up. Waiting until we have the cirlceCI stuff working properly before I merge this

**Comment by bdolly** [comment]
@cgreene could we get saucelabs hooked up soon so we can merge this in?

**Comment by cgreene** [comment]
@bdolly : SAUCE_USERNAME and SAUCE_ACCESS_KEY environment variables are set.

**Comment by cgreene** [comment]
@bdolly : a couple issues here with SauceLabs SauceConnect  - their "latest" build is a couple years out of date. They have blamed this for issues with CircleCI in the past:
https://support.saucelabs.com/customer/portal/questions/15881491-error-failed-to-bring-up-tunnel-vm-intermittently

I switched to their latest version 4.4.1 and I still have issues setting up the tunnel from CircleCI. I have filed a ticket about both the out of date version and the remaining difficulties connecting from CircleCI. The changes to circle.yml to setup the tunnel are incomplete as I wait for their reply.

**Comment by bdolly** [comment]
@dhimmel [last CI build passed ](https://circleci.com/gh/cognoma/frontend/33) I think we're good to merge this PR whenever you give it your nod of approval

**Comment by dhimmel** [comment]
> @dhimmel last CI build passed I think we're good to merge this PR whenever you give it your nod of approval

Nod. FYI, no need for my approval. As long as there is an approval from any project member.

**Pull request merged**
