### PR TITLE
Addition of develop branch and AngularJS scaffolding

### PR DESCRIPTION
**Pull request by bdolly**
Created develop branch in order to structure the frontend repo in a [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) style. 

Setup a frontend application scaffolding based on [angularjs-gulp-browserify-boilerplate](angularjs-gulp-browserify-boilerplate) for a more modularized and scalable architecture. This structure was then modified to use an [ui-router](https://ui-router.github.io/tutorial/ng1/hellosolarsystem) [angular component hierarchy model](https://docs.angularjs.org/guide/component) in order for easier functional encapsulation. Plenty of documentation is provided in README.md of the develop branch.

### CODE REVIEW

**Comment by dhimmel** [comment]
Thanks @bdolly for the pull request. I don't have the expertise to review it but I think you chatted with @bvasko, who can probably help with the review. You two can also work together to identify which technology stack you think is best. Cheers!

**Comment by dhimmel** [comment]
@bdolly you can go ahead and merge. I'll let you decide which of the three merge method options you think is best.

**Comment by awm33** [comment]
Discussing branching in https://github.com/cognoma/frontend/pull/16 since we may be using it for deployment. Please look here before merging

**Comment by bdolly** [comment]
@awm33 I do agree that if we're doing CI/continuous deployment that it would be good to create a `production` branch and I think most of the gitflow tools can be config'd to use a branch other than `master` for production code. I will make this merge then push another PR up with an updated README and a `production` branch. 

Keep me in the loop on how the other groups have their branching models setup so we can stay in sync.

**Comment by awm33** [comment]
@bdolly 👍  sounds good

**Pull request merged**
