### PR TITLE
Bugfix/duplicate disease results

### PR DESCRIPTION
**Pull request by ramenhog**
## Issue Number
#153 

## Purpose/Implementation Notes
* Prevent already added params from showing up in the search results also

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Functional tests
* params that are added to query no longer show up in search results

## Checklist

_Put an `x` in the boxes that apply._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ramenhog** [comment]
@dongbohu @mhuyck I want to write a unit test for this bug, but `_filteredSearchResults` is a private function. Is there a better way to test this without making it public function?

**Comment by dongbohu** [comment]
@ramenhog I took a look at the code but couldn't think of a better way.

**Comment by ramenhog** [comment]
@dongbohu should I make it public just for the sole purpose of testing it?...that feels weird

**Comment by dongbohu** [comment]
@ramenhog I agree it will be weird to set a function to public solely for testing purpose. Can you just test the public function that calls this one?

**Pull request merged**
