### PR TITLE
Incorporate work from #8 into master

### PR DESCRIPTION
**Pull request by dhimmel**
In this pull request, I've tried to take the work of @BobMiller and @keenleo from #8 and create a git history that tracks each user's contribution.

@keenleo: it looks like you appear as two identities. You should pick the name and email you would like to author git commits under and make sure GitHub is aware of this email.

@BobMiller and @keenleo: can you look through the history and see if it is accurate? Is this code appropriate for master? Is there additional cleaning up we should do before merging this? It looks like some files may be duplicated. If so, you can create a pull request into `dhimmel/frontend:keenleo-rebase` or mention the issues here (but please no posting edits to files that aren't tracked by git).

CCing @gwaygenomics.

### CODE REVIEW

**Comment by dhimmel** [comment]
I noticed we may be having some line ending inconsistencies. We may want to address [this issue](https://help.github.com/articles/dealing-with-line-endings/) now or later.

**Comment by dhimmel** [comment]
> @keenleo: it looks like you appear as two identities. You should pick the name and email you would like to author git commits under and make sure GitHub is aware of this email.

If we get this worked out before merging this pull request, we won't have to force update master in the future.

**Comment by dhimmel** [comment]
@BobMiller @keenleo: any updates? Can we work on getting this pull request merged so your work makes it into the repository?

**Comment by keenleo** [comment]
I'll commit the merged files tonight.

**Comment by keenleo** [comment]
@dhimmel  I've merged the files into my fork. I placed the static HTML version in a folder called "html_version". The angular single page app version is in the "app" folder.

Does it really matter if we set the default EOL to crlf or lf? Is there a pro or con to either?

**Comment by dhimmel** [comment]
> @dhimmel I've merged the files into my fork.

@keenleo I assume you're talking about the following commit: https://github.com/keenleo/frontend/commit/75bf538629486239d294a6b14dd060c2c3404bcd. Looks really nice, but the problem is that your commit doesn't seem to preserve the authorship of @BobMiller. It's essential that future work build on top of the history in this pull request.

Would you like me to add your latest changes as a new commit on top of this pull request? Then we can merge this pull request.

**Comment by dhimmel** [comment]
> Does it really matter if we set the default EOL to crlf or lf? Is there a pro or con to either?

Probably not. I like `\n` for simplicity over `\r\n`. Let's defer action on this issue until a later time.

**Comment by keenleo** [comment]
@dhimmel I cloned the pr/9 branch and merged the files. I tried to publish the commit but received an authentication error that I do not have access. I doubled checked and I am logged in. Could this be a permissions issue?

**Comment by dhimmel** [comment]
@keenleo, the issue is that you don't have write access to the remote repo (either `dhimmel/frontend` or `cognoma/frontend` depending on how you cloned this pull request branch). What you should do is to push your updates to a branch where you do have write access (any branch in `keenleo/frontend`). Then you can link to it here, or you can create a pull request in the `keenleo-rebase` branch of `dhimmel/frontend` (since every update to my `keenleo-rebase` branch gets added to this pull request).

Does that make sense?

**Comment by dhimmel** [comment]
@keenleo I took the additional changes you had on your [master branch](https://github.com/keenleo/frontend/tree/1722327ec51eae83c1790537892f104bddb203f9) and squashed them into a single commit (6cb233f715360acac189e2adb7d563bf2224ea3a). I think we should get this merged as it represents all the work so far.

For future changes, you can make a pull request into the master branch of `cognoma/frontend`, which should be less confusing. @cgreene can you provide an approval for the merge to proceed?

**Comment by cgreene** [comment]
@dhimmel squashed commit looks good to me. Includes the changes that were discussed here.

**Pull request merged**
