### PR TITLE
Add UX folder and First Use Case

### PR DESCRIPTION
**Pull request by keenleo**
Created UX folder and add Process Model for fist use case

### CODE REVIEW

**Comment by dhimmel** [comment]
Regarding `UX/use_cases/one/process_models/User Actions Level 1.png`: should we avoid filenames with spaces? Not essential but nice for convenience.

**Comment by cgreene** [comment]
@dhimmel @keenleo I agree with avoiding spaces in filenames for convenience.

**Comment by bdolly** [comment]
@dhimmel @keenleo how do you feel about me closing this PR down because we spun up a UXUI repo in the project?

**Comment by cgreene** [comment]
:+1:

**Comment by dhimmel** [comment]
> @dhimmel @keenleo how do you feel about me closing this PR down because we spun up a UXUI repo in the project?

@bdolly makes sense to me. Ball is in your court.

@keenleo, don't be shy asking for git help if you would like to make another pull request with some of these changes.

**Pull request closed without merging**
